spring.application.name=APIDesbravadores

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
api.security.token.secret=${JWT_SECRET}
jwt.validity=3600
spring.jpa.show-sql=true